### ISSUE TITLE
different color not come

### ISSUE THREAD

**Issue by jigarrdesai** [kauffecup/react-bubble-chart#3]
hello, i implement this code but buble is not coming with different color
and i use with following data
var testData = [{
   _id: "1",        // unique id (required)
   value: "100",      // used to determine relative size of bubbles (required)
   sentiment :"positive",
   colorValue: "#a50f15", // used to determine color
   selected: true,  // if true will use selectedColor/selectedTextColor for circle/text
},{
   _id: "2",        // unique id (required)
   value: "100",      // used to determine relative size of bubbles (required)
   sentiment :"positive",
   colorValue: "#c6dbef", // used to determine color
   selected: true,  // if true will use selectedColor/selectedTextColor for circle/text
},{
   _id: "3",        // unique id (required)
   value: "100",      // used to determine relative size of bubbles (required)
   sentiment :"positive",
   colorValue: "#9ecae1", // used to determine color
   selected: true,  // if true will use selectedColor/selectedTextColor for circle/text
},{
   _id: "4",        // unique id (required)
   value: "100",      // used to determine relative size of bubbles (required)
   sentiment :"#4292c6",
   colorValue: "#4292c6", // used to determine color
   selected: true,  // if true will use selectedColor/selectedTextColor for circle/text
},{
   _id: "5",        // unique id (required)
   value: "100",      // used to determine relative size of bubbles (required)

   colorValue: "positive", // used to determine color
   sentiment :"positive",
   selected: true,  // if true will use selectedColor/selectedTextColor for circle/text
},{
   _id: "6",        // unique id (required)
   value: "100",      // used to determine relative size of bubbles (required)
   sentiment :"positive",
   colorValue: "positive", // used to determine color
   selected: true,  // if true will use selectedColor/selectedTextColor for circle/text
}];
render method is 
 render () {

```
console.log(this.props.data);
var data = testData.map(d => ({
   _id: d._id,
  value: d.value,
  colorValue: d.sentiment,
  selected: d.selected
}));

return( <ReactBubbleChart
  className="my-cool-chart"
  colorLegend={colorLegend}
  data={data}
  selectedColor={colorLegend}
  selectedTextColor="#d9d9d9"
//  fixedDomain={{min: -1, max: 40000000}}
  onClick={this.bubbleClick}
  legend={true}
  legendSpacing={0}
  tooltip={false}
  tooltipProps={this.tooltipProps}
  tooltipFunc={this.tooltipFunc}
/> )
```

  }

**Comment by parthms** [comment]
You have to define a colorLegend array. In your bubble chart, the second prop (colorLegend) is referring to something undefined. In addition, selectedColor accepts a hex string not an array. Try this:

``` javascript
const testData = [
    {
        _id: 'test 1',
        value: 100,
        colorValue: -0.5,
        selected: false
    },
    {
        _id: 'test 2',
        value: 200,
        colorValue: 0.01,
        selected: false
    },
    {
        _id: 'test 3',
        value: 300,
        colorValue: 0.3,
        selected: false
    }
];

const colorLegend = [
  // reds from dark to light
  {color: "#67000d", textColor: '#fee0d2', text: 'Negative'},
  {color: "#a50f15", textColor: '#fee0d2'},
  {color: "#cb181d", textColor: '#fee0d2'},
  "#ef3b2c",
  "#fb6a4a",
  "#fc9272",
  "#fcbba1",
  "#fee0d2",
  //neutral grey
  {color: "#f0f0f0", text: 'Neutral'},
  // blues from light to dark
  "#deebf7",
  "#c6dbef",
  "#9ecae1",
  "#6baed6",
  "#4292c6",
  {color: "#2171b5", textColor: '#deebf7'},
  {color: '#08519c', textColor: '#deebf7'},
  {color: "#08306b", textColor: '#deebf7', text: 'Positive'}
];

class BubbleChart extends Component {
    render() {
        return (
            <div style={{ height: '500px'}}>
                <ReactBubbleChart
                    colorLegend={ colorLegend }
                    legend={ true }
                    selectedColor='#737373'
                    selectedTextColor='#d9d9d9'
                    fixedDomain={{ min: -1, max: 1 }}
                    data={ testData }
                />
            </div>
        )
    }
}

export default BubbleChart;
```

**Comment by kauffecup** [comment]
hey, sorry i've been slacking a bit! @jigarrdesai was your issue resolved by @parthms?
